name: CI - Build and Test

# runs in very push in main or in every pull request 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # my repo clone
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Config Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      # 3. Project dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./smart-budget

      # Paso 4: Ejecuta el linter
      # Y a este también
      - name: Run linting
        run: npm run lint
        working-directory: ./smart-budget

      # Paso 5: Construye la aplicación
      # Y a este también
      - name: Build application
        run: npm run build
        working-directory: ./smart-budget