name: CI - Build and Test

# runs on every push to main and every pull request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Clone repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configure Node.js with cache
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'smart-budget/package-lock.json'

      # 3. Install dependencies (faster and reproducible)
      - name: Install dependencies
        run: npm ci
        working-directory: ./smart-budget

      # 4. Run linter
      - name: Run linting
        run: npm run lint
        working-directory: ./smart-budget

      # 5. Build application
      - name: Build application
        run: npm run build
        working-directory: ./smart-budget

      # 6. Upload build artifact (proof of successful build)
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: smart-budget/dist
